-- =========================================================
-- Home Credit Default Risk: Full Schema & Bulk Ingestion
-- =========================================================

SET GLOBAL local_infile = 1;

CREATE DATABASE IF NOT EXISTS home_credit;
USE home_credit;

-- 1. application_train (122 Columns)
CREATE TABLE IF NOT EXISTS application_train (
    SK_ID_CURR INT PRIMARY KEY,
    TARGET TINYINT,
    NAME_CONTRACT_TYPE VARCHAR(50),
    CODE_GENDER VARCHAR(10),
    FLAG_OWN_CAR VARCHAR(5),
    FLAG_OWN_REALTY VARCHAR(5),
    CNT_CHILDREN INT,
    AMT_INCOME_TOTAL DECIMAL(15, 2),
    AMT_CREDIT DECIMAL(15, 2),
    AMT_ANNUITY DECIMAL(15, 2),
    AMT_GOODS_PRICE DECIMAL(15, 2),
    NAME_TYPE_SUITE VARCHAR(50),
    NAME_INCOME_TYPE VARCHAR(50),
    NAME_EDUCATION_TYPE VARCHAR(50),
    NAME_FAMILY_STATUS VARCHAR(50),
    NAME_HOUSING_TYPE VARCHAR(50),
    REGION_POPULATION_RELATIVE DECIMAL(10, 6),
    DAYS_BIRTH INT,
    DAYS_EMPLOYED INT,
    DAYS_REGISTRATION DECIMAL(12, 2),
    DAYS_ID_PUBLISH INT,
    OWN_CAR_AGE DECIMAL(10, 2),
    FLAG_MOBIL TINYINT,
    FLAG_EMP_PHONE TINYINT,
    FLAG_WORK_PHONE TINYINT,
    FLAG_CONT_MOBILE TINYINT,
    FLAG_PHONE TINYINT,
    FLAG_EMAIL TINYINT,
    OCCUPATION_TYPE VARCHAR(50),
    CNT_FAM_MEMBERS DECIMAL(5, 1),
    REGION_RATING_CLIENT INT,
    REGION_RATING_CLIENT_W_CITY INT,
    WEEKDAY_APPR_PROCESS_START VARCHAR(20),
    HOUR_APPR_PROCESS_START INT,
    REG_REGION_NOT_LIVE_REGION TINYINT,
    REG_REGION_NOT_WORK_REGION TINYINT,
    LIVE_REGION_NOT_WORK_REGION TINYINT,
    REG_CITY_NOT_LIVE_CITY TINYINT,
    REG_CITY_NOT_WORK_CITY TINYINT,
    LIVE_CITY_NOT_WORK_CITY TINYINT,
    ORGANIZATION_TYPE VARCHAR(100),
    EXT_SOURCE_1 DECIMAL(10, 8),
    EXT_SOURCE_2 DECIMAL(10, 8),
    EXT_SOURCE_3 DECIMAL(10, 8),
    APARTMENTS_AVG DECIMAL(10, 4),
    BASEMENTAREA_AVG DECIMAL(10, 4),
    YEARS_BEGINEXPLUATATION_AVG DECIMAL(10, 4),
    YEARS_BUILD_AVG DECIMAL(10, 4),
    COMMONAREA_AVG DECIMAL(10, 4),
    ELEVATORS_AVG DECIMAL(10, 4),
    ENTRANCES_AVG DECIMAL(10, 4),
    FLOORSMAX_AVG DECIMAL(10, 4),
    FLOORSMIN_AVG DECIMAL(10, 4),
    LANDAREA_AVG DECIMAL(10, 4),
    LIVINGAPARTMENTS_AVG DECIMAL(10, 4),
    LIVINGAREA_AVG DECIMAL(10, 4),
    NONLIVINGAPARTMENTS_AVG DECIMAL(10, 4),
    NONLIVINGAREA_AVG DECIMAL(10, 4),
    APARTMENTS_MODE DECIMAL(10, 4),
    BASEMENTAREA_MODE DECIMAL(10, 4),
    YEARS_BEGINEXPLUATATION_MODE DECIMAL(10, 4),
    YEARS_BUILD_MODE DECIMAL(10, 4),
    COMMONAREA_MODE DECIMAL(10, 4),
    ELEVATORS_MODE DECIMAL(10, 4),
    ENTRANCES_MODE DECIMAL(10, 4),
    FLOORSMAX_MODE DECIMAL(10, 4),
    FLOORSMIN_MODE DECIMAL(10, 4),
    LANDAREA_MODE DECIMAL(10, 4),
    LIVINGAPARTMENTS_MODE DECIMAL(10, 4),
    LIVINGAREA_MODE DECIMAL(10, 4),
    NONLIVINGAPARTMENTS_MODE DECIMAL(10, 4),
    NONLIVINGAREA_MODE DECIMAL(10, 4),
    APARTMENTS_MEDI DECIMAL(10, 4),
    BASEMENTAREA_MEDI DECIMAL(10, 4),
    YEARS_BEGINEXPLUATATION_MEDI DECIMAL(10, 4),
    YEARS_BUILD_MEDI DECIMAL(10, 4),
    COMMONAREA_MEDI DECIMAL(10, 4),
    ELEVATORS_MEDI DECIMAL(10, 4),
    ENTRANCES_MEDI DECIMAL(10, 4),
    FLOORSMAX_MEDI DECIMAL(10, 4),
    FLOORSMIN_MEDI DECIMAL(10, 4),
    LANDAREA_MEDI DECIMAL(10, 4),
    LIVINGAPARTMENTS_MEDI DECIMAL(10, 4),
    LIVINGAREA_MEDI DECIMAL(10, 4),
    NONLIVINGAPARTMENTS_MEDI DECIMAL(10, 4),
    NONLIVINGAREA_MEDI DECIMAL(10, 4),
    FONDKAPREMONT_MODE VARCHAR(50),
    HOUSETYPE_MODE VARCHAR(50),
    TOTALAREA_MODE DECIMAL(10, 4),
    WALLSMATERIAL_MODE VARCHAR(50),
    EMERGENCYSTATE_MODE VARCHAR(10),
    OBS_30_CNT_SOCIAL_CIRCLE DECIMAL(10, 2),
    DEF_30_CNT_SOCIAL_CIRCLE DECIMAL(10, 2),
    OBS_60_CNT_SOCIAL_CIRCLE DECIMAL(10, 2),
    DEF_60_CNT_SOCIAL_CIRCLE DECIMAL(10, 2),
    DAYS_LAST_PHONE_CHANGE DECIMAL(10, 2),
    FLAG_DOCUMENT_2 TINYINT,
    FLAG_DOCUMENT_3 TINYINT,
    FLAG_DOCUMENT_4 TINYINT,
    FLAG_DOCUMENT_5 TINYINT,
    FLAG_DOCUMENT_6 TINYINT,
    FLAG_DOCUMENT_7 TINYINT,
    FLAG_DOCUMENT_8 TINYINT,
    FLAG_DOCUMENT_9 TINYINT,
    FLAG_DOCUMENT_10 TINYINT,
    FLAG_DOCUMENT_11 TINYINT,
    FLAG_DOCUMENT_12 TINYINT,
    FLAG_DOCUMENT_13 TINYINT,
    FLAG_DOCUMENT_14 TINYINT,
    FLAG_DOCUMENT_15 TINYINT,
    FLAG_DOCUMENT_16 TINYINT,
    FLAG_DOCUMENT_17 TINYINT,
    FLAG_DOCUMENT_18 TINYINT,
    FLAG_DOCUMENT_19 TINYINT,
    FLAG_DOCUMENT_20 TINYINT,
    FLAG_DOCUMENT_21 TINYINT,
    AMT_REQ_CREDIT_BUREAU_HOUR DECIMAL(10, 2),
    AMT_REQ_CREDIT_BUREAU_DAY DECIMAL(10, 2),
    AMT_REQ_CREDIT_BUREAU_WEEK DECIMAL(10, 2),
    AMT_REQ_CREDIT_BUREAU_MON DECIMAL(10, 2),
    AMT_REQ_CREDIT_BUREAU_QRT DECIMAL(10, 2),
    AMT_REQ_CREDIT_BUREAU_YEAR DECIMAL(10, 2)
);

-- 2. bureau (17 Columns)
CREATE TABLE IF NOT EXISTS bureau (
    SK_ID_CURR INT,
    SK_ID_BUREAU INT PRIMARY KEY,
    CREDIT_ACTIVE VARCHAR(50),
    CREDIT_CURRENCY VARCHAR(20),
    DAYS_CREDIT INT,
    CREDIT_DAY_OVERDUE INT,
    DAYS_CREDIT_ENDDATE DECIMAL(10, 2),
    DAYS_ENDDATE_FACT DECIMAL(10, 2),
    AMT_CREDIT_MAX_OVERDUE DECIMAL(15, 2),
    CNT_CREDIT_PROLONG INT,
    AMT_CREDIT_SUM DECIMAL(15, 2),
    AMT_CREDIT_SUM_DEBT DECIMAL(15, 2),
    AMT_CREDIT_SUM_LIMIT DECIMAL(15, 2),
    AMT_CREDIT_SUM_OVERDUE DECIMAL(15, 2),
    CREDIT_TYPE VARCHAR(100),
    DAYS_CREDIT_UPDATE INT,
    AMT_ANNUITY DECIMAL(15, 2)
);

-- 3. previous_application (37 Columns)
CREATE TABLE IF NOT EXISTS previous_application (
    SK_ID_PREV INT PRIMARY KEY,
    SK_ID_CURR INT,
    NAME_CONTRACT_TYPE VARCHAR(50),
    AMT_ANNUITY DECIMAL(15, 2),
    AMT_APPLICATION DECIMAL(15, 2),
    AMT_CREDIT DECIMAL(15, 2),
    AMT_DOWN_PAYMENT DECIMAL(15, 2),
    AMT_GOODS_PRICE DECIMAL(15, 2),
    WEEKDAY_APPR_PROCESS_START VARCHAR(20),
    HOUR_APPR_PROCESS_START INT,
    FLAG_LAST_APPL_PER_CONTRACT VARCHAR(5),
    NFLAG_LAST_APPL_IN_DAY TINYINT,
    RATE_DOWN_PAYMENT DECIMAL(10, 6),
    RATE_INTEREST_PRIMARY DECIMAL(10, 6),
    RATE_INTEREST_PRIVILEGED DECIMAL(10, 6),
    NAME_CASH_LOAN_PURPOSE VARCHAR(100),
    NAME_CONTRACT_STATUS VARCHAR(50),
    DAYS_DECISION INT,
    NAME_PAYMENT_TYPE VARCHAR(50),
    CODE_REJECT_REASON VARCHAR(50),
    NAME_TYPE_SUITE VARCHAR(50),
    NAME_CLIENT_TYPE VARCHAR(50),
    NAME_GOODS_CATEGORY VARCHAR(100),
    NAME_PORTFOLIO VARCHAR(50),
    NAME_PRODUCT_TYPE VARCHAR(50),
    CHANNEL_TYPE VARCHAR(100),
    SELLERPLACE_AREA INT,
    NAME_SELLER_INDUSTRY VARCHAR(100),
    CNT_PAYMENT DECIMAL(5, 1),
    NAME_YIELD_GROUP VARCHAR(50),
    PRODUCT_COMBINATION VARCHAR(100),
    DAYS_FIRST_DRAWING DECIMAL(10, 2),
    DAYS_FIRST_DUE DECIMAL(10, 2),
    DAYS_LAST_DUE_1ST_VERSION DECIMAL(10, 2),
    DAYS_LAST_DUE DECIMAL(10, 2),
    DAYS_TERMINATION DECIMAL(10, 2),
    NFLAG_INSURED_ON_APPROVAL DECIMAL(5, 1)
);

-- 4. installments_payments (8 Columns)
CREATE TABLE IF NOT EXISTS installments_payments (
    SK_ID_PREV INT,
    SK_ID_CURR INT,
    NUM_INSTALMENT_VERSION DECIMAL(10, 2),
    NUM_INSTALMENT_NUMBER INT,
    DAYS_INSTALMENT DECIMAL(10, 2),
    DAYS_ENTRY_PAYMENT DECIMAL(10, 2),
    AMT_INSTALMENT DECIMAL(15, 2),
    AMT_PAYMENT DECIMAL(15, 2)
);

-- Ingestion section (Empty strings converted to NULLs automatically)
LOAD DATA LOCAL INFILE '/tmp/raw/application_train.csv'
INTO TABLE application_train
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '/tmp/raw/bureau.csv'
INTO TABLE bureau
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '/tmp/raw/previous_application.csv'
INTO TABLE previous_application
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '/tmp/raw/installments_payments.csv'
INTO TABLE installments_payments
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;